### ISSUE TITLE
from viewer import draw

### ISSUE THREAD

**Issue by JiweiTian** [ITSEG-MQ/Adv-attack-and-defense-on-driving-model#1]
Hi,
"from viewer import draw"
Is viewer a self-defined function or third-party module?
It can't work.

**Comment by LGNRoy** [comment]
Thanks for reminding. It seems that we forget to upload this file.
We will upload it tomorrow.

**Comment by ITSEG-MQ** [comment]
the viewer.py file is updated

**Comment by JiweiTian** [comment]
Thank you very much!
